name: Build Test

on: [ push, pull_request ]
jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64'
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - run: (Get-content yarn.lock) | Foreach-Object {$_ -replace "registry.npm.taobao.org", "r.cnpmjs.org"} | Set-Content yarn.lock
      - run: yarn
      - run: yarn electron:build
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.gz
    
